version: "3.9"
services:
  web:
    build: .
    environment:
      MESSAGE: "Hello World"
      HOST: "0.0.0.0"
      PORT: 5000
    ports:
      - "5000:5000"
    networks:
      - core_npm_hcinet

networks:
  core_npm_hcinet:
    external: true
